# Generated by Django 4.1.1 on 2023-03-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
