# Generated by Django 4.1.1 on 2023-03-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
