# Generated by Django 4.1.1 on 2023-03-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_profile_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hn_username",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
