# Generated by Django 4.1.1 on 2023-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_profile_city_profile_country_profile_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="who_wants_to_be_hired_titles",
        ),
        migrations.AddField(
            model_name="profile",
            name="who_wants_to_be_hired_title",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
    ]
