# Generated by Django 4.1.1 on 2023-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_remove_profile_who_wants_to_be_hired_titles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="willing_to_relocate",
            field=models.CharField(default="No", max_length=256),
        ),
    ]
