# Generated by Django 4.1.1 on 2023-03-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_alter_profile_willing_to_relocate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="capacity",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
