# Generated by Django 4.1.7 on 2023-04-04 15:24

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("company_homepage_link", models.URLField(blank=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True, editable=False, populate_from="name"
                    ),
                ),
                ("emails", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True, editable=False, populate_from="name"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True, editable=False, populate_from="name"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("who_is_hiring_id", models.IntegerField()),
                ("who_is_hiring_title", models.CharField(max_length=25)),
                ("who_is_hiring_comment_id", models.IntegerField()),
                ("hn_username", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("levels_of_experience", models.TextField(blank=True)),
                ("capacity", models.TextField(blank=True)),
                ("compensation_summary", models.TextField(blank=True, null=True)),
                ("years_of_experience", models.TextField(blank=True)),
                ("locations", models.TextField(blank=True)),
                ("cities", models.TextField(blank=True)),
                ("countries", models.CharField(blank=True, max_length=100)),
                ("is_remote", models.BooleanField(default=False)),
                ("is_onsite", models.BooleanField(default=False)),
                ("remote_timezones", models.TextField(blank=True)),
                ("company_job_application_link", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("names_of_the_contact_person", models.TextField(blank=True)),
                ("emails", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.company"
                    ),
                ),
                (
                    "job_titles",
                    models.ManyToManyField(
                        blank=True, related_name="job", to="jobs.title"
                    ),
                ),
                (
                    "technologies_used",
                    models.ManyToManyField(
                        blank=True, related_name="job", to="jobs.technology"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
