# Generated by Django 4.1.7 on 2023-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_posttitle_posttechnology_post_jobs_post_technologies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="company_job_application_link",
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
