# Generated by Django 4.1.7 on 2023-05-12 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_post_company_job_application_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("email_is_valid", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=256)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="jobs.company")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
