# Generated by Django 4.1.7 on 2023-05-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_email_post_alter_email_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="compliment",
            field=models.TextField(blank=True),
        ),
    ]
