# Generated by Django 4.1.7 on 2023-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_company_compliment"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="email_is_generic",
            field=models.BooleanField(default=True),
        ),
    ]
