# Generated by Django 4.1.7 on 2023-05-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_email_email_is_generic"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
