# Generated by Django 4.1.7 on 2023-06-29 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_email_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="submitted_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
