GENERIC_KEYWORDS = [
    "jobs",
    "apply",
    "info",
    "joinourteam",
    "admin",
    "billing",
    "contact",
    "customerservice",
    "help",
    "marketing",
    "media",
    "newsletter",
    "sales",
    "support",
    "webmaster",
    "hiring",
    "recruiting",
    "sear-recruiting",
    "work",
    "careers",
    "hello",
    "careers+hn",
    "talent",
    "jobs.tech",
    "tech.jobs",
    "90COS.Hiring.Office",
    "office",
    "hiring",
    "employment",
    "ops",
    "people.ops",
    "join",
    "dev-products",
    "hn_recruiting",
    "recruiting",
    "hr",
    "recruiting+hn",
    "hi",
    "team",
    "growthlead",
    "social",
    "post",
    "talentacquisition",
    "jobs+hn",
    "vehiclesoftwarerecruiting",
    "founders",
    "earninhiring",
    "career",
]

EXCLUDED_TECHNOLOGIES = ["", " "]

EXCLUDED_TITLES = ["", " "]
